FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    cmake \
    make \
    libstdc++-12-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY rag-platform/docker-requirement.txt ./requirements.txt

ENV CMAKE_ARGS="-DLLAMA_BLAS=OFF"
ENV FORCE_CMAKE=1

RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

COPY rag-platform/src /app/src
ENV PYTHONPATH=/app/src

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

